name: Build Blog
on:
  push:
    branches: [ main ]
    paths:
      - '_blog/**'
      - '_templates/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Install dependencies
        run: npm install
        
      - name: Generate blog pages
        run: node scripts/generate-blog.js
        
      - name: Commit and push if changed
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --local user.email "ad.schlee@gmail.com"
          git config --local user.name "AdSchl2E"
          git add -A
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-generate blog pages" && git push https://x-access-token:${GH_PAT}@github.com/AdSchl2E/Plumbing-24-Service-Inc.git HEAD:main)